package view;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;


import javafx.scene.control.Button;

import javafx.scene.control.ProgressBar;

import javafx.scene.control.ListView;

import javafx.scene.layout.AnchorPane;

import javafx.scene.image.ImageView;


public class GlavniProzorController {
	@FXML
	private Button btnPlejlista;
	@FXML
	private ProgressBar progresBar;
	@FXML
	private ImageView mjut;
	@FXML
	private AnchorPane glavniPanel;
	@FXML
	private ListView listaDrugara;

	// Event Listener on Button[#btnPlejlista].onAction
    public void printaj(ActionEvent event) {
    	btnPlejlista.setText("juhuhu");
    }
	// Event Listener on ImageViewmjut.onMouseClicked
	@FXML
	public void mjutuj(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#listaDrugara].onMouseClicked
	@FXML
	public void osvjeziListu(ActionEvent event) {
		// TODO Autogenerated
	}
}
